spring.application.name=gestion-incidencias
server.port=8081

# Desactivar autoconfiguració de base de dades
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration





